#pragma config(Motor,  port5,           wheel1,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           wheel2,        tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "ServoUtil.h" // Include the functions from the other file

task main()
{
    bool servo1State = false;
    bool servo2State = false;

    while (true)
    {
        toggleServo(wheel1, 0, 180, servo1State, Btn5U); // Call the function for servo 1
        //toggleServo(wheel2, -127, 127, servo2State, Btn6U); // Call the function for servo 2

        moveServo(wheel2, 90, Btn6U);
        moveServo(wheel2, 0, Btn6D);

        // Add your additional code or functionalities here

        // Example: Drive motors using joysticks
        //motor[port4] = vexRT[Ch3]; // Replace port4 with the correct motor port
        //motor[port5] = vexRT[Ch2]; // Replace port5 with the correct motor port
    }
}
