#pragma config(Sensor, in1,    IRAnalog,       sensorAnalog)
#pragma config(Sensor, dgtl3,  irReceive1,     sensorDigitalIn)
#pragma config(Sensor, dgtl2, irReceive2,     sensorDigitalIn)
#pragma config(Motor,  port2,           motor1,        tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{


	while(true){

		clearDebugStream();

		//writeDebugStream("%d", SensorValue[irReceive1]);
		writeDebugStreamLine("%d", SensorValue[IRAnalog]);

		writeDebugStreamLine("%d", SensorValue[irReceive1]);
		writeDebugStreamLine("%d", SensorValue[irReceive2]);


	}



}
