#pragma config(Sensor, dgtl1,  irReceive,      sensorDigitalIn)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{


	while(true){
		if (irReceive == true){
		}

	}


}
