#pragma config(Sensor, dgtl1,  irLeft,         sensorDigitalIn)
#pragma config(Sensor, dgtl10, irRight,        sensorDigitalIn)
#pragma config(Motor,  port2,           leftDrive,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           rightDrive,    tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool lineFollowingEnabled = false; // Flag to control line following mode

task main()
{
  clearTimer(T1);

  while (true)
  {
    // Check if a joystick button is pressed to enable line following
    if (vexRT[Btn8U] == 1) // Use Btn5U as the start button (you can change this)
    {
      lineFollowingEnabled = true;
      clearTimer(T1);
    }

    // Check if a joystick button is pressed to disable line following
    if (vexRT[Btn8D] == 1) // Use Btn5D as the stop button (you can change this)
    {
      lineFollowingEnabled = false;
      motor[leftDrive] = 0; // Stop left motor
      motor[rightDrive] = 0; // Stop right motor
    }

    if (lineFollowingEnabled)
    {
      if (SensorValue[irLeft] == 0) // left over white
      {
        motor[leftDrive] = -25;
        motor[rightDrive] = 75 + 500 * (time1[T1] / 1000);
      }
      else if (SensorValue[irRight] == 0) // right over white
      {
        motor[leftDrive] = 95 + 500 * (time1[T1] / 1000);
        motor[rightDrive] = -35;
      }
      else
      {
        motor[leftDrive] = 127;
        motor[rightDrive] = 80;

        clearTimer(T1);
      }
    }
    else
    {
      // Manual driving mode
      // You can add your manual control code here using other joystick buttons and axes

    	float leftPower = vexRT[Ch3]+vexRT[Ch1];
			float rightPower = vexRT[Ch3]-vexRT[Ch1];
			// slow mode
			if (vexRT[Btn5U]) {
				motor[leftDrive] = 0.3 * leftPower;
				motor[rightDrive] = 0.3 * rightPower;
			} else {
				motor[leftDrive] = leftPower;
				motor[rightDrive] = rightPower;
			}


    }
  }
}
