#pragma config(Sensor, dgtl1,  irLeft,         sensorDigitalIn)
#pragma config(Sensor, dgtl2,  irRight,        sensorDigitalIn)
#pragma config(Motor,  port2,           leftDrive,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           rightDrive,    tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{


	while(true){


		clearDebugStream();
	writeDebugStream("%d", SensorValue[irLeft]);
	// 40 , 45
	if (SensorValue[irLeft] == 0) { // left over white
		motor[leftDrive] = 25;
		motor[rightDrive] = 37;
	} else {
		motor[leftDrive] = 27;
		motor[rightDrive] = 23;
	}
	}




}
