#pragma config(Sensor, in1,    potentiometer,  sensorAnalog)
#pragma config(Motor,  port9,           armMotor,      tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

		const float kF = 34; // Proportional constant

    while (true)
    {



    		int currentPosition = SensorValue[potentiometer];

    		float ticksPerDegree = 4096/300;


    		clearDebugStream();
        writeDebugStreamLine("Potentiometer Value: %d", currentPosition);

        float theta = (currentPosition - 2770) / ticksPerDegree;

        writeDebugStreamLine("theta: %.6f", theta);

        float ff = kF * cosDegrees(theta);

        writeDebugStreamLine("Feedforward Value: %.6f", ff);



        // Read the joystick's vertical axis value.
        int joystickValue;
        if (vexRT[Btn6U]) {
        	joystickValue = 70;
        } else if (vexRT[Btn6D]) {
        	joystickValue = -70;
        } else {
        	joystickValue = 0;
        }

        // Map the joystick value to the motor power range (-127 to 127).
        int motorPower;
        if (theta < -20) {
        	motorPower = joystickValue;
        } else {
        	motorPower = joystickValue + ff;
        }


        // Set the motor's power based on the joystick input.

        writeDebugStreamLine("Motor Power: %.6f", motorPower);
        motor[armMotor] = motorPower;

    }
}
