#pragma config(Motor,  port9,           armMotor,      tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
    while (true)
    {
        // Read the joystick's vertical axis value.
        int joystickValue = vexRT[Ch2]; // Assuming you are using the Ch2 channel for the joystick.

        // Map the joystick value to the motor power range (-127 to 127).
        int motorPower = joystickValue;

        // Set the motor's power based on the joystick input.
        motor[armMotor] = motorPower;

    }
}
