#pragma config(Motor,  port4,           servo4,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           servo3,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           servo2,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           servo1,        tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

    while (true)
    {
        if (vexRT[Btn5U] == 1) // close
        {
            // Set the servo positions
        	motor[servo1] = 100;
        	motor[servo2] = -40;
        }
        else if (vexRT[Btn5D] == 1) //open
        {
            motor[servo1] = -39;
        		motor[servo2] = 90;
        }

        if (vexRT[Btn6U] == 1) // close
        {
            // Set the servo positions
        	motor[servo3] = 128;
        	motor[servo4] = -128;
        }
        else if (vexRT[Btn6D] == 1) //open
        {
            motor[servo3] = -128;
        		motor[servo4] = 128;
        }


    }
}
