#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           clawServo,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "ServoUtil.h"

task main()
{

	bool clawState = false;

	while(true){

		float leftPower = vexRT[Ch3]+vexRT[Ch1];
		float rightPower = vexRT[Ch3]-vexRT[Ch1];
		// slow mode
		if (vexRT[Btn5U]) {
			motor[leftMotor] = 0.3 * leftPower;
			motor[rightMotor] = 0.3 * rightPower;
		} else {
			motor[leftMotor] = leftPower;
			motor[rightMotor] = rightPower;
		}
/*
		if (vexRT[Btn6U]) {
			motor[armMotor] = 1;
		} else {
			motor[armMotor] = -1;
		}
*/
		/*
		if (vexRT[Btn6D]) {
			motor[clawServo] = 180; // open
		} else {
			motor[clawServo] = 0; // close
		}
		*/

		//toggleServo(clawServo, 0, 180, clawState, vexRT[Btn6D]);





	}




}
