#pragma config(Motor,  port2,           leftDrive,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           rightDrive,    tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool prevDrive = false;
bool autoState = false;
bool curDrive = false;

bool prevFwd = false;
bool curFwd = false;










void moveFWD() {
	clearTimer(T1);
    while ((time1[T1] / 1000) > 2.5) { // Assuming stopBtn represents a button press
        motor[leftDrive] = 50;
  			motor[rightDrive] = 50;
    }
}
























task main()
{
    while(true)
    {

    		prevDrive = curDrive;
    		if (vexRT[Btn5D]) {
		    	curDrive = true;
		    } else {
		    	curDrive = false;
		    }

        if(curDrive && !prevDrive) { // Rising Edge for Mode switch
            autoState = !autoState;
        }



        if (autoState) {
        		prevFwd = curFwd;
		    		if (vexRT[Ch3] > 15) {
				    	curFwd = true;
				    } else {
				    	curFwd = false;
				    }

				    if(curFwd && !prevFwd) { // Rising edge FWD
				    	moveFWD();
       			}





        } else { // manual
        	motor[leftDrive] = vexRT[Ch3] + vexRT[Ch1];
  				motor[rightDrive] = vexRT[Ch3] - vexRT[Ch1];
        }

    }
}
