#pragma config(Sensor, in1,    potentiometer,  sensorAnalog)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
    while (true)
    {
        // Read the potentiometer value
        int currentPosition = SensorValue[potentiometer];

        clearDebugStream();
        writeDebugStreamLine("Potentiometer Value: %d", currentPosition);


    }
}
