#pragma config(Sensor, in1,    potentiometer,  sensorAnalog)
#pragma config(Motor,  port5,           armMotor,      tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
    while (true)
    {
        // Read the potentiometer value
        int currentPosition = SensorValue[potentiometer];

        clearDebugStream();
        writeDebugStreamLine("Potentiometer Value: %d", currentPosition);

        if (vexRT[Btn6U]) { // Vein Score
		      motor[armMotor] = 127;
		    } else if (vexRT[Btn6D]) { // Vein Score
		      motor[armMotor] = -75;
		    } else {
		    	motor[armMotor] = 0;
		    }




    }
}
