#pragma config(Motor,  port7,           armMotor,      tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port8,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port9,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	bool clawState = false;

	while(true){

		float leftPower = vexRT[Ch3]-vexRT[Ch1];
		float rightPower = vexRT[Ch3]+vexRT[Ch1];
		// slow mode
		if (vexRT[Btn5U]) {
			motor[leftMotor] = 0.3 * leftPower;
			motor[rightMotor] = 0.3 * rightPower;
		} else {
			motor[leftMotor] = leftPower;
			motor[rightMotor] = rightPower;
		}

		if (vexRT[Btn6U]) {
			motor[armMotor] = 100;
		} else if (vexRT[Btn6D]) {
			motor[armMotor] = -100;
		} else {
			motor[armMotor] = 0;
		}

		/*
		if (vexRT[Btn6D]) {
			motor[clawServo] = 180; // open
		} else {
			motor[clawServo] = 0; // close
		}
		*/

		//toggleServo(clawServo, 0, 180, clawState, vexRT[Btn6D]);





	}




}
