#pragma config(Sensor, in1,    potentiometer,  sensorAnalog)
#pragma config(Sensor, dgtl3,  irLeft,         sensorDigitalIn)
#pragma config(Sensor, dgtl4,  irRight,        sensorDigitalIn)
#pragma config(Motor,  port2,           leftDrive,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           leftJoint,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           armMotor,      tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           leftClaw,      tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           rightClaw,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           rightJoint,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           rightDrive,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Subsystems/drivetrain.h"
#include "Subsystems/arm.h"
#include "Subsystems/veinGrabber.h"

task main()
{
	bool clawToggle = false;
	int prevClaw = false;

	bool dualStick = true;

  while (true)
  {

  	if (vexRT[Btn8U]) { // Vein Score
      setArmSetpoint(1500);
      openJoint();
    } else if (vexRT[Btn8L]) { // Vein Pickup
      setArmSetpoint(1500);
      closeJoint();
      openClaw();
    } else if (vexRT[Btn8R]) { // High Artery
      setArmSetpoint(1500);
    } else if (vexRT[Btn8D]) { // Low Artery
      setArmSetpoint(1500);
    } else if (vexRT[Btn6U]) {
    	nudgeUp();
    } else if (vexRT[Btn6D]) {
    	nudgeDown();
    }

   updateArm(); // Update the arm position using the PID controller








    // CLAW
    // Rising edge detector
		if (vexRT[Btn5D] && !prevClaw) {
		    // This will set intakeToggle to true if it was previously false
		    // and intakeToggle to false if it was previously true,
		    // providing a toggling behavior.
		    clawToggle = !clawToggle;
		}

		// Using the toggle variable to control the robot.
		if (clawToggle) {
		    closeClaw();
		}
		else {
		    openClaw();
		}

    prevClaw = vexRT[Btn5D];









  	// Drive
    if (vexRT[Btn7L]) {
    	dualStick = false;
    } else if (vexRT[Btn7R]) {
    	dualStick = true;
    }

    if (dualStick) {
    	arcadeDrive(vexRT[Ch3], vexRT[Ch1], vexRT[Btn5U]);
    } else {
    	arcadeDrive(vexRT[Ch3], vexRT[Ch4], vexRT[Btn5U]);
    }


    if (vexRT[Btn7U]) {
    	lineFollowing(vexRT[Btn7D]);
    }




  }
}
