#pragma config(Sensor, in1,    armPotentiometer, sensorPotentiometer)
#pragma config(Motor,  port2,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           leftMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//drive code - left joystick
	//slow drive - map to 5U
	//arm code - map to right joystick, potentiometer or however it is spelled
	//arm positions - map max to 6u, min to 6d
	//arm slow mode - map to 5D
	//180 degree turn, map to 8D (math or testing needed)
	//KEEP THE ARM UP - HOW WILL THIS WORK? IF POTENTIOMETER, POWER BASED ON VALUE. IF LIMIT SWITCH, JUST ENGINEERING?

	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	motor[armMotor] = 0;
	bool slow = false;
	bool slowArm = false;
	bool letGoArm = true;
	bool turning = false;
	bool armAutoPos = false;
	bool letGoPos = true;
	int maxArmVal, minArmVal;
	while(true){
		//move control
		float forwardStick = vexRT[Ch4];
		float sideStick = vexRT[Ch3];
		float leftPower = vexRT[Ch4]+vexRT[Ch3];
		float rightPower = vexRT[Ch4]-vexRT[Ch3];
		float max = abs(forwardStick) + abs(sideStick);
		float denominator;
		if(max > 127){
			denominator = max;
		} else {
			denominator = 127;
		}
		if(turning == false){
			if(slow == true){
				motor[leftMotor] = leftPower / denominator * 127 / 2;
				motor[rightMotor] = rightPower / denominator * 127 / 2;
			} else {
				motor[leftMotor] = leftPower / denominator * 127;
				motor[rightMotor] = rightPower / denominator * 127;
			}
		}
		//slow control
		int upperButtonPosition = vexRT[Btn5U];
		if(slow == false && upperButtonPosition == 1){
			slow = true;
			wait1Msec(10);
		} else if(slow == true && upperButtonPosition == 1){
			slow = false;
			wait1Msec(10);
		}
		//arm control
		float armStick = vexRT[Ch1];
		if(armAutoPos == false){
			if(slowArm == true){
				if(SensorValue[armPotentiometer] > minArmVal && SensorValue[armPotentiometer] < maxArmVal){
					motor[armMotor] = armStick / 2;
				} else {
					if((SensorValue[armPotentiometer] > minArmVal && armStick < 0)||(SensorValue[armPotentiometer] < maxArmVal && armStick > 0)){
						motor[armMotor] = 0;
					}
					motor[armMotor] = armStick / 2;
				}
			} else {
					if(SensorValue[armPotentiometer] > minArmVal && SensorValue[armPotentiometer] < maxArmVal){
						motor[armMotor] = armStick;
					} else {
						if((SensorValue[armPotentiometer] > minArmVal && armStick < 0)||(SensorValue[armPotentiometer] < maxArmVal && armStick > 0)){
							motor[armMotor] = 0;
						}
						motor[armMotor] = armStick;
					}
			}
		}
		//arm slow control
		int lowerButtonPosition = vexRT[Btn5D];
		if(slowArm == false && lowerButtonPosition == 1 && letGoArm == true){
			slowArm = true;
			letGoArm = false;
			while(lowerButtonPosition == 1){
				letGoArm = false;
			}
			letGoArm = true;
		} else if(slowArm == true && lowerButtonPosition == 1 && letGoArm == true){
			letGoArm = false;
			while(lowerButtonPosition == 1){
				letGoArm = false;
			}
			letGoArm = true;
			slowArm = false;
		}
		//arm positions
		int maxArmPos = vexRT[Btn6U];
		int minArmPos = vexRT[Btn6D];
		//TBA WITH POSITION
		if(maxArmPos == 1 && letGoPos == true && armAutoPos == false){
			armAutoPos = true;
			while(maxArmPos == 1){
				letGoPos = false;
			}
			letGoPos = true;
			while(SensorValue[armPotentiometer] < maxArmVal){
				motor[armMotor]  = 127;
			}
			motor[armMotor]  = 0;
			armAutoPos = false;
		}
		if(minArmPos == 1 && letGoPos == true && armAutoPos == false){
			armAutoPos = true;
			while(minArmPos == 1){
				letGoPos = false;
			}
			letGoPos = true;
			while(SensorValue[armPotentiometer] > minArmVal){
				motor[armMotor] = -127;
			}
			motor[armMotor] = 0;		    // Motor on is on full at -127 power backward
			armAutoPos = false;
		}
		//180 turn
		int turnButtonPos = vexRT[Btn8D];
		if(turnButtonPos == 1){
			turning = true;
			motor[rightMotor] = -127;		    // Motor on is on full at -127 power backward
			motor[leftMotor]  = -127;			// Motor on is run at full (127) power forward
			wait1Msec(500);
			turning = false;
		}
	}



}
